# Generated by Django 4.0.3 on 2022-04-05 11:06

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0003_lectureruser_studentuser'),
    ]

    operations = [
        migrations.AddField(
            model_name='lectureruser',
            name='role',
            field=models.TextField(default='Преподаватель', max_length=30),
        ),
        migrations.AddField(
            model_name='studentuser',
            name='role',
            field=models.TextField(default='Студент', max_length=30),
        ),
    ]
