# Generated by Django 3.1.3 on 2022-02-19 20:26

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0003_auto_20220219_2317'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='profile',
            name='college',
        ),
        migrations.RemoveField(
            model_name='profile',
            name='major',
        ),
        migrations.AddField(
            model_name='profile',
            name='role',
            field=models.CharField(choices=[('lecturer', 'Преподаватель'), ('student', 'Студент'), ('administrator', 'Администратор')], default='student', max_length=30),
        ),
    ]
