# Generated by Django 4.0.3 on 2022-04-08 19:25

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0004_lectureruser_role_studentuser_role'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='lectureruser',
            name='role',
        ),
        migrations.RemoveField(
            model_name='studentuser',
            name='role',
        ),
    ]
