# Generated by Django 3.1.3 on 2022-02-26 10:11

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0004_auto_20220226_1256'),
    ]

    operations = [
        migrations.AlterField(
            model_name='student',
            name='course_number',
            field=models.IntegerField(null=True),
        ),
    ]
