# Generated by Django 3.1.3 on 2022-02-26 10:45

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0005_auto_20220226_1311'),
    ]

    operations = [
        migrations.AlterField(
            model_name='student',
            name='course_number',
            field=models.IntegerField(blank=True, null=True),
        ),
    ]
