# Generated by Django 4.0.3 on 2022-04-08 19:32

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0005_remove_lectureruser_role_remove_studentuser_role'),
    ]

    operations = [
        migrations.AddField(
            model_name='emailuser',
            name='role',
            field=models.TextField(default='', max_length=30),
        ),
    ]
