# Generated by Django 3.1.3 on 2022-02-19 21:48

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0005_auto_20220220_0013'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='coursepage',
            name='slug',
        ),
        migrations.AddField(
            model_name='coursepage',
            name='general_info',
            field=models.TextField(default='test', verbose_name='Общая информация'),
            preserve_default=False,
        ),
        migrations.CreateModel(
            name='Group',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=30)),
                ('courses', models.ManyToManyField(to='main.CoursePage')),
                ('parent_grop', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='main.group')),
                ('subgroups', models.ManyToManyField(related_name='_group_subgroups_+', to='main.Group')),
            ],
        ),
        migrations.AddField(
            model_name='profile',
            name='groups',
            field=models.ManyToManyField(to='main.Group'),
        ),
    ]
