# Generated by Django 3.1.3 on 2022-02-26 10:47

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0006_auto_20220226_1345'),
    ]

    operations = [
        migrations.AddField(
            model_name='lecturer',
            name='link',
            field=models.URLField(blank=True),
        ),
    ]
