# Generated by Django 3.1.3 on 2022-02-19 22:04

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0006_auto_20220220_0048'),
    ]

    operations = [
        migrations.AddField(
            model_name='coursepage',
            name='slug',
            field=models.SlugField(default='Replacement', max_length=255, unique=True, verbose_name='URL'),
            preserve_default=False,
        ),
    ]
