# Generated by Django 4.0.3 on 2022-04-10 18:40

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0007_alter_emailuser_role'),
    ]

    operations = [
        migrations.CreateModel(
            name='Material',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=30)),
                ('descripiton', models.TextField(blank=True)),
            ],
        ),
        migrations.AlterModelOptions(
            name='lectureruser',
            options={'verbose_name': 'LectorUser'},
        ),
        migrations.AlterModelOptions(
            name='studentuser',
            options={'verbose_name': 'StudentUser'},
        ),
        migrations.CreateModel(
            name='File',
            fields=[
                ('material_ptr', models.OneToOneField(auto_created=True, on_delete=django.db.models.deletion.CASCADE, parent_link=True, primary_key=True, serialize=False, to='main.material')),
                ('file_material', models.FileField(upload_to='files/%Y/%m/%d')),
                ('is_published', models.BooleanField(default=True)),
            ],
            bases=('main.material',),
        ),
        migrations.CreateModel(
            name='Url',
            fields=[
                ('material_ptr', models.OneToOneField(auto_created=True, on_delete=django.db.models.deletion.CASCADE, parent_link=True, primary_key=True, serialize=False, to='main.material')),
                ('address', models.URLField()),
            ],
            bases=('main.material',),
        ),
    ]
