# Generated by Django 3.1.3 on 2022-02-19 22:13

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0007_coursepage_slug'),
    ]

    operations = [
        migrations.AlterField(
            model_name='coursepage',
            name='slug',
            field=models.SlugField(max_length=255, verbose_name='URL'),
        ),
    ]
