# Generated by Django 4.0.3 on 2022-04-11 15:14

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0008_material_alter_lectureruser_options_and_more'),
    ]

    operations = [
        migrations.RenameField(
            model_name='material',
            old_name='descripiton',
            new_name='description',
        ),
        migrations.CreateModel(
            name='Announcement',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('text', models.TextField()),
                ('sender', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='my_announcements', to=settings.AUTH_USER_MODEL)),
            ],
        ),
    ]
