# Generated by Django 4.0.3 on 2022-04-11 16:33

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0008_material_alter_lectureruser_options_and_more'),
    ]

    operations = [
        migrations.RenameField(
            model_name='material',
            old_name='descripiton',
            new_name='description',
        ),
    ]
