# Generated by Django 4.0.3 on 2022-04-11 15:20

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0009_rename_descripiton_material_description_announcement'),
    ]

    operations = [
        migrations.AddField(
            model_name='announcement',
            name='receivers',
            field=models.ManyToManyField(related_name='recieved_announcements', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AlterField(
            model_name='announcement',
            name='sender',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='sent_announcements', to=settings.AUTH_USER_MODEL),
        ),
    ]
