# Generated by Django 4.0.3 on 2022-04-24 20:07

from django.db import migrations, models
import django.db.models.deletion
import embed_video.fields


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0009_rename_descripiton_material_description'),
    ]

    operations = [
        migrations.CreateModel(
            name='Video',
            fields=[
                ('material_ptr', models.OneToOneField(auto_created=True, on_delete=django.db.models.deletion.CASCADE, parent_link=True, primary_key=True, serialize=False, to='main.material')),
                ('video_material', embed_video.fields.EmbedVideoField()),
            ],
            options={
                'verbose_name_plural': 'Video_material',
            },
            bases=('main.material',),
        ),
        migrations.AlterModelOptions(
            name='material',
            options={'verbose_name': 'Материал', 'verbose_name_plural': 'Материалы'},
        ),
    ]
