# Generated by Django 4.0.3 on 2022-04-24 20:36

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0010_video_alter_material_options'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='video',
            options={},
        ),
    ]
